# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/OP4AD9/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/OP4AD9

PRODUCT_COPY_FILES += \
    vendor/oplus/OP4AD9/proprietary/odm/bin/hw/vendor.nxp.hardware.nfc@1.2-service:$(TARGET_COPY_OUT_ODM)/bin/hw/vendor.nxp.hardware.nfc@1.2-service \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/General_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Global_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Handset_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Headset_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Speaker_cal.acdb \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/hi846:$(TARGET_COPY_OUT_ODM)/etc/camera/config/hi846 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/imx471:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx471 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/imx586:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx586 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oplus/OP4AD9/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oplus/OP4AD9/proprietary/odm/etc/init/init.SN100x.nfc.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.SN100x.nfc.rc \
    vendor/oplus/OP4AD9/proprietary/odm/etc/init/vendor.nxp.hardware.nfc@1.2-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.nxp.hardware.nfc@1.2-service.rc \
    vendor/oplus/OP4AD9/proprietary/odm/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc-nci.conf \
    vendor/oplus/OP4AD9/proprietary/odm/etc/libnfc-nxp-pnscr.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc-nxp-pnscr.conf \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/libnfc-mtp-SN100.conf_19161:$(TARGET_COPY_OUT_ODM)/etc/nfc/libnfc-mtp-SN100.conf_19161 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/libnfc-nci.conf_19161:$(TARGET_COPY_OUT_ODM)/etc/nfc/libnfc-nci.conf_19161 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/nfc_conf_ref:$(TARGET_COPY_OUT_ODM)/etc/nfc/nfc_conf_ref \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/nfc_fw_ref:$(TARGET_COPY_OUT_ODM)/etc/nfc/nfc_fw_ref \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/sn100u.bin_sn100t_fw_01_10_53:$(TARGET_COPY_OUT_ODM)/etc/nfc/sn100u.bin_sn100t_fw_01_10_53 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/sn100u.bin_sn100t_fw_01_10_57:$(TARGET_COPY_OUT_ODM)/etc/nfc/sn100u.bin_sn100t_fw_01_10_57 \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/st21nfc_fw.bin_st21h:$(TARGET_COPY_OUT_ODM)/etc/nfc/st21nfc_fw.bin_st21h \
    vendor/oplus/OP4AD9/proprietary/odm/etc/nfc/st21nfc_fw7.bin_st21h:$(TARGET_COPY_OUT_ODM)/etc/nfc/st21nfc_fw7.bin_st21h \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_bmi26x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_bmi26x_0.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_cct.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct_rear.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_icm4x6xx.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_icm4x6xx.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_lsm6dso.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_lsm6dso.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/config/kona_qrd_sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_sx933x_0.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oplus/OP4AD9/proprietary/odm/etc/wifi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlan.elf \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/aw8697_haptic.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/aw8697_haptic_170.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic_170.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/aw8697_haptic_235.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic_235.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/aw8697_haptic_235_19161.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw8697_haptic_235_19161.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/fastchg/19161/oplus_vooc_fw.bin:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/19161/oplus_vooc_fw.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/tp/19161/FW_S3908_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/19161/FW_S3908_BOE.img \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/tp/19161/FW_S6SY771_SAMSUNG.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19161/FW_S6SY771_SAMSUNG.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/tp/19161/FW_S6SY771_SAMSUNG_FAE.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/19161/FW_S6SY771_SAMSUNG_FAE.bin \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/tp/19161/LIMIT_S3908_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/19161/LIMIT_S3908_BOE.img \
    vendor/oplus/OP4AD9/proprietary/odm/firmware/tp/19161/LIMIT_S6SY771_SAMSUNG.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/19161/LIMIT_S6SY771_SAMSUNG.img \
    vendor/oplus/OP4AD9/proprietary/odm/lib/libsn100u_fw.so:$(TARGET_COPY_OUT_ODM)/lib/libsn100u_fw.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensor.gc02m0b.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensor.gc02m0b.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensor.hi846.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensor.hi846.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensor.imx471.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensor.imx471.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensor.imx586.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensor.imx586.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensormodule.gc02m0b_1.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.gc02m0b_1.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensormodule.gc02m0b_2.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.gc02m0b_2.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensormodule.ofilm_imx586.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.ofilm_imx586.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensormodule.truly_hi846.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.truly_hi846.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.sensormodule.truly_imx471.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.truly_imx471.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.tuned.sm8250_gc02m0b_19161.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sm8250_gc02m0b_19161.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.tuned.sm8250_ofilm_imx586_19161.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sm8250_ofilm_imx586_19161.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.tuned.sm8250_truly_hi846_19161.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sm8250_truly_hi846_19161.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/camera/com.qti.tuned.sm8250_truly_imx471_19161.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.sm8250_truly_imx471_19161.bin \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/nfc_nci.nqx.default.hw.so:$(TARGET_COPY_OUT_ODM)/lib64/nfc_nci.nqx.default.hw.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/vendor.nxp.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.nxp.hardware.nfc@1.0.so \
    vendor/oplus/OP4AD9/proprietary/odm/lib64/vendor.nxp.hardware.nfc@1.1.so:$(TARGET_COPY_OUT_ODM)/lib64/vendor.nxp.hardware.nfc@1.1.so \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b00 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b01 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b02 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b03 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b04 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b05 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b06 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.b07 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/alipay.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/alipay.mdt \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b00 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b01 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b02 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b03 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b04 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b05 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b06 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.b07 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp.mdt \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b00 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b01 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b02 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b03 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b04 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b05 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b06 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.b07 \
    vendor/oplus/OP4AD9/proprietary/odm/vendor/firmware/goodixfp_G6.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/goodixfp_G6.mdt \
    vendor/oplus/OP4AD9/proprietary/vendor/bin/hw/android.hardware.keymaster@4.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@4.0-service-qti \
    vendor/oplus/OP4AD9/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/oplus/OP4AD9/proprietary/vendor/etc/ltm_config_samsung_amb655uv01_amoled_fhd+_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_samsung_amb655uv01_amoled_fhd+_panel_with_DSC.xml \
    vendor/oplus/OP4AD9/proprietary/vendor/etc/qdcm_calib_data_samsung_amb655uv01_amoled_fhd+_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_samsung_amb655uv01_amoled_fhd+_panel_with_DSC.xml \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b00 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b01 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b02 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b03 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b04 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b05 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b06 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.b07 \
    vendor/oplus/OP4AD9/proprietary/vendor/firmware/image/opluseid.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/image/opluseid.mdt \
    vendor/oplus/OP4AD9/proprietary/vendor/lib64/libkeymasterdeviceutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterdeviceutils.so \
    vendor/oplus/OP4AD9/proprietary/vendor/lib64/libkeymasterprovision.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterprovision.so \
    vendor/oplus/OP4AD9/proprietary/vendor/lib64/libkeymasterutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterutils.so \
    vendor/oplus/OP4AD9/proprietary/vendor/lib64/libqcbor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcbor.so \
    vendor/oplus/OP4AD9/proprietary/vendor/lib64/libqtikeymaster4.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqtikeymaster4.so

PRODUCT_PACKAGES += \
    manifest_nfc_sn100t
