# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter op4ad9,$(TARGET_DEVICE)),)

endif
